# Generated by Django 5.1.5 on 2025-01-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
