# Generated by Django 5.1.5 on 2025-01-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_contactsubmission_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='doctor',
            name='days',
            field=models.CharField(default='Monday - Friday', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='details',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='time',
            field=models.CharField(default='9:00 AM - 5:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='caption',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
