# Generated by Django 5.1.5 on 2025-01-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_doctor_contact_info_doctor_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='choice',
            field=models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('book_appointment', 'Book an Appointment'), ('other', 'Other')], default='general_inquiry', max_length=50),
        ),
    ]
