# Generated by Django 5.1.5 on 2025-01-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_contactsubmission_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
