# Generated by Django 5.1.5 on 2025-01-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_contactsubmission_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='🩺', help_text='Enter the icon ', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
