# Generated by Django 5.1.5 on 2025-01-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_remove_service_image_service_details_service_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='path',
            field=models.CharField(default='/services/', max_length=100),
        ),
    ]
