# Generated by Django 5.1.5 on 2025-02-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_alter_banner_image_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.TextField(default=''),
        ),
    ]
